//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace echo.BLL.Info
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class InfoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new InfoEntities object using the connection string found in the 'InfoEntities' section of the application configuration file.
        /// </summary>
        public InfoEntities() : base("name=InfoEntities", "InfoEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InfoEntities object.
        /// </summary>
        public InfoEntities(string connectionString) : base(connectionString, "InfoEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new InfoEntities object.
        /// </summary>
        public InfoEntities(EntityConnection connection) : base(connection, "InfoEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Information> Informations
        {
            get
            {
                if ((_Informations == null))
                {
                    _Informations = base.CreateObjectSet<Information>("Informations");
                }
                return _Informations;
            }
        }
        private ObjectSet<Information> _Informations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rate> Rates
        {
            get
            {
                if ((_Rates == null))
                {
                    _Rates = base.CreateObjectSet<Rate>("Rates");
                }
                return _Rates;
            }
        }
        private ObjectSet<Rate> _Rates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MoscowDelivery> MoscowDeliveris
        {
            get
            {
                if ((_MoscowDeliveris == null))
                {
                    _MoscowDeliveris = base.CreateObjectSet<MoscowDelivery>("MoscowDeliveris");
                }
                return _MoscowDeliveris;
            }
        }
        private ObjectSet<MoscowDelivery> _MoscowDeliveris;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<echoNews> echoNews
        {
            get
            {
                if ((_echoNews == null))
                {
                    _echoNews = base.CreateObjectSet<echoNews>("echoNews");
                }
                return _echoNews;
            }
        }
        private ObjectSet<echoNews> _echoNews;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Informations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInformations(Information information)
        {
            base.AddObject("Informations", information);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRates(Rate rate)
        {
            base.AddObject("Rates", rate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MoscowDeliveris EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMoscowDeliveris(MoscowDelivery moscowDelivery)
        {
            base.AddObject("MoscowDeliveris", moscowDelivery);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the echoNews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToechoNews(echoNews echoNews)
        {
            base.AddObject("echoNews", echoNews);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfoModel", Name="echoNews")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class echoNews : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new echoNews object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="newsDate">Initial value of the NewsDate property.</param>
        /// <param name="avail">Initial value of the avail property.</param>
        public static echoNews CreateechoNews(global::System.Int32 id, global::System.DateTime newsDate, global::System.Boolean avail)
        {
            echoNews echoNews = new echoNews();
            echoNews.Id = id;
            echoNews.NewsDate = newsDate;
            echoNews.avail = avail;
            return echoNews;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NewsDate
        {
            get
            {
                return _NewsDate;
            }
            set
            {
                OnNewsDateChanging(value);
                ReportPropertyChanging("NewsDate");
                _NewsDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NewsDate");
                OnNewsDateChanged();
            }
        }
        private global::System.DateTime _NewsDate;
        partial void OnNewsDateChanging(global::System.DateTime value);
        partial void OnNewsDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Header
        {
            get
            {
                return _Header;
            }
            set
            {
                OnHeaderChanging(value);
                ReportPropertyChanging("Header");
                _Header = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Header");
                OnHeaderChanged();
            }
        }
        private global::System.String _Header;
        partial void OnHeaderChanging(global::System.String value);
        partial void OnHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean avail
        {
            get
            {
                return _avail;
            }
            set
            {
                OnavailChanging(value);
                ReportPropertyChanging("avail");
                _avail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("avail");
                OnavailChanged();
            }
        }
        private global::System.Boolean _avail;
        partial void OnavailChanging(global::System.Boolean value);
        partial void OnavailChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfoModel", Name="Information")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Information : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Information object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Information CreateInformation(global::System.Int32 id)
        {
            Information information = new Information();
            information.Id = id;
            return information;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String News
        {
            get
            {
                return _News;
            }
            set
            {
                OnNewsChanging(value);
                ReportPropertyChanging("News");
                _News = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("News");
                OnNewsChanged();
            }
        }
        private global::System.String _News;
        partial void OnNewsChanging(global::System.String value);
        partial void OnNewsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfoModel", Name="MoscowDelivery")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MoscowDelivery : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MoscowDelivery object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static MoscowDelivery CreateMoscowDelivery(global::System.Int32 id, global::System.Decimal price)
        {
            MoscowDelivery moscowDelivery = new MoscowDelivery();
            moscowDelivery.Id = id;
            moscowDelivery.Price = price;
            return moscowDelivery;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfoModel", Name="Rate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rate object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="rateUS">Initial value of the RateUS property.</param>
        public static Rate CreateRate(global::System.Int32 id, global::System.Decimal rateUS)
        {
            Rate rate = new Rate();
            rate.Id = id;
            rate.RateUS = rateUS;
            return rate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RateUS
        {
            get
            {
                return _RateUS;
            }
            set
            {
                OnRateUSChanging(value);
                ReportPropertyChanging("RateUS");
                _RateUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RateUS");
                OnRateUSChanged();
            }
        }
        private global::System.Decimal _RateUS;
        partial void OnRateUSChanging(global::System.Decimal value);
        partial void OnRateUSChanged();

        #endregion

    
    }

    #endregion

    
}
